# Generated by Django 4.1.1 on 2022-09-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_descriptions',
            field=models.TextField(default=12313, max_length=500),
            preserve_default=False,
        ),
    ]
